Object subclass: #CObject
instanceVariableNames: '
	name
	type
	subtype
	elements
	params
	comment
	enumeration
	function
	value
	isClassMethod
	selectorParams
	selector
	callParams
	var
	checkCall
'
classVariableNames: '
'
poolDictionaries: '
' !


! CObject class methods!


!"End of class methods block"


! CObject methods!


name: aValue
	name := aValue.
":Section Category
accessing
:End"
!"end new method selector: "


elements: aValue
	elements := aValue.
":Section Category
accessing
:End"
!"end new method selector: "


elements
	^ elements.
":Section Category
accessing
:End"
!"end new method selector: "


comment: aValue
	comment := aValue.
":Section Category
accessing
:End"
!"end new method selector: "


comment
	^ comment.
":Section Category
accessing
:End"
!"end new method selector: "


enumeration: aValue
	enumeration := aValue.
":Section Category
accessing
:End"
!"end new method selector: "


enumeration
	^ enumeration.
":Section Category
accessing
:End"
!"end new method selector: "


function: aValue
	function := aValue.
":Section Category
accessing
:End"
!"end new method selector: "


function
	^ function.
":Section Category
accessing
:End"
!"end new method selector: "


value: aValue
	value := aValue.
":Section Category
accessing
:End"
!"end new method selector: "


value
	^ value.
":Section Category
accessing
:End"
!"end new method selector: "


isClassMethod: aValue
	isClassMethod := aValue.
":Section Category
accessing
:End"
!"end new method selector: "


isClassMethod
	^ isClassMethod.
":Section Category
accessing
:End"
!"end new method selector: "


selectorParams: aValue
	selectorParams := aValue.
":Section Category
accessing
:End"
!"end new method selector: "


selectorParams
	^ selectorParams.
":Section Category
accessing
:End"
!"end new method selector: "


selector: aValue
	selector := aValue.
":Section Category
accessing
:End"
!"end new method selector: "


selector
	^ selector.
":Section Category
accessing
:End"
!"end new method selector: "


callParams: aValue
	callParams := aValue.
":Section Category
accessing
:End"
!"end new method selector: "


callParams
	^ callParams.
":Section Category
accessing
:End"
!"end new method selector: "


var: aValue
	var := aValue.
":Section Category
accessing
:End"
!"end new method selector: "


var
	^ var.
":Section Category
accessing
:End"
!"end new method selector: "


checkCall: aValue
	checkCall := aValue.
":Section Category
accessing
:End"
!"end new method selector: "


checkCall
	^ checkCall.
":Section Category
accessing
:End"
!"end new method selector: "


params
	^ params.
":Section Category
accessing
:End"
!"end new method selector: "


params: aValue
	params := aValue.
":Section Category
accessing
:End"
!"end new method selector: "


subtype
	^ subtype.
":Section Category
accessing
:End"
!"end new method selector: "


subtype: aValue
	subtype := aValue.
":Section Category
accessing
:End"
!"end new method selector: "


type
	^ type.
":Section Category
accessing
:End"
!"end new method selector: "


type: aValue
	type := aValue.
":Section Category
accessing
:End"
!"end new method selector: "


name
	^ name.
":Section Category
accessing
:End"
!"end new method selector: "


!"End of methods block"

